import kb

slov = {'timetable': {'msg': "1 КУРС",
                                      'kb': kb.keyboard_1course,
                                      'attch': "photo-209576287_457239929"},
                        'course_1': {'msg': "1 КУРС",
                                     'kb': kb.keyboard_1course,
                                     'attch': None},
                        'course_2': {'msg': "2 КУРС",
                                     'kb': kb.keyboard_2course,
                                     'attch': None},
                        'course_3': {'msg': "3 КУРС",
                                     'kb': kb.keyboard_3course,
                                     'attch': None},
                        'course_4': {'msg': "4 КУРС",
                                     'kb': kb.keyboard_4course,
                                     'attch': None},
                        "Отмена_button": {'msg': None,
                                          'kb': kb.keyboard_main,
                                          'attch': "photo-209576287_457239928"},
                        'МТ_button':{'msg': "1 КУРС",
                                     'kb': kb.keyboard_MT,
                                     'attch': None,
                                     },
                        'ИП_button':{'msg': "1 КУРС",
                                     'kb': kb.keyboard_IP,
                                     'attch': None,
                                     },
                        'МТ_button':{'msg': '1 КУРС',
                                     'kb': kb.keyboard_MT,
                                     'attch': None,
                                     },
                        'МР_button':{'msg': "3 КУРС",
                                     'kb': kb.keyboard_MR,
                                     'attch': None,
                                     },
                        'К_button':{'msg': "1 КУРС",
                                     'kb': kb.keyboard_K,
                                     'attch': None,
                                     },
                        }